### ISSUE TITLE
writeSTEP is not implemented?

### ISSUE THREAD

**Issue by miroslav-frank** [OpenWebCAD/node-occ#32]
Am I right, that writeSTEP is not implemented, as I get only empty STL file with text header and tests are missing for this method? Or is just something broken at my side?

**Comment by mftaha** [comment]
I think that you mean writeSTL, writeSTEP works for me but not writeSTL

**Comment by miroslav-frank** [comment]
Yeah, you're right. Thanks for bumping. I changed the post.

**Comment by ceremcem** [comment]
Below code results with segmentation fault: 

```js
var occ = require('occ').occ
var box = occ.makeBox([0,0,0],[100,100,50])
var cyl = occ.makeCylinder([50,50,-10],[50,50,60],40)
box = occ.cut(box,cyl)
occ.writeSTL("somefile.stl",box)
```

# Stack trace
```console
backtrace:
#0  0x00007fffe4269d2a in StlAPI_Writer::Write(TopoDS_Shape const&, char const*) () from ./node_modules/occ/occt-7.2.0/lib/libTKSTL.so.7
No symbol table info available.
#1  0x00007ffff5a2a95d in writeSTL(Nan::FunctionCallbackInfo<v8::Value> const&) () at /usr/include/c++/8/bits/basic_string.h:2281
        B = {<TopoDS_Builder> = {<No data fields>}, <No data fields>}
        C = {<TopoDS_Shape> = {myTShape = {entity = 0x24ead80}, myLocation = {myItems = {myNode = {entity = 0x0}}}, myOrient = TopAbs_FORWARD}, <No data fields>}
        writer = {myASCIIMode = false}
        filename = "somefile.stl"
        shapes = std::__cxx11::list = {[0] = 0x23bf750}
#2  0x00007ffff5a1c1cc in Nan::imp::FunctionCallbackWrapper (info=...) at ../node_modules/nan/nan_callbacks_12_inl.h:174
        obj = {val_ = 0x7fffffffc8e8}
        callback = 0x7ffff5a2a800 <writeSTL(Nan::FunctionCallbackInfo<v8::Value> const&)>
        cbinfo = {info_ = @0x7fffffffc7f0, data_ = {val_ = 0x2304fd0}, static kHolderIndex = <optimized out>, static kIsolateIndex = <optimized out>, static kReturnValueDefaultValueIndex = <optimized out>, static kReturnValueIndex = <optimized out>, static kDataIndex = <optimized out>, static kCalleeIndex = <optimized out>, static kContextSaveIndex = <optimized out>, static kArgsLength = <optimized out>}
#3  0x0000000000ac4ca3 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
No symbol table info available.
#4  0x0000000000b43758 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
No symbol table info available.
#5  0x0000000000b44179 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
No symbol table info available.
#6  0x0000321a3960437d in ?? ()
No symbol table info available.
#7  0x0000321a396042c1 in ?? ()
No symbol table info available.
#8  0x00007fffffffc9e0 in ?? ()
No symbol table info available.
#9  0x0000000000000006 in ?? ()
No symbol table info available.
#10 0x00007fffffffca68 in ?? ()
No symbol table info available.
#11 0x0000321a397c2962 in ?? ()
No symbol table info available.
#12 0x0000340ed0602311 in ?? ()
No symbol table info available.
#13 0x000004427f453309 in ?? ()
No symbol table info available.
#14 0x0000000600000000 in ?? ()
No symbol table info available.
#15 0x000013f8b663fe99 in ?? ()
No symbol table info available.
#16 0x000023f225876621 in ?? ()
No symbol table info available.
#17 0x00003a3f69691b69 in ?? ()
No symbol table info available.
#18 0x000004427f453309 in ?? ()
No symbol table info available.
#19 0x000013f8b6638f89 in ?? ()
No symbol table info available.
#20 0x000013f8b663fe99 in ?? ()
No symbol table info available.
#21 0x00003a3f69691b69 in ?? ()
No symbol table info available.
#22 0x00003a3f69692bd9 in ?? ()
No symbol table info available.
#23 0x000019e078583971 in ?? ()
No symbol table info available.
#24 0x00007fffffffcb00 in ?? ()
No symbol table info available.
#25 0x0000321a397c1ef0 in ?? ()
No symbol table info available.
#26 0x00003a3f69692c21 in ?? ()
No symbol table info available.
#27 0x00003a3f69692c49 in ?? ()
No symbol table info available.
#28 0x00003a3f69692b01 in ?? ()
No symbol table info available.
#29 0x00003a3f69692b91 in ?? ()
No symbol table info available.
#30 0x00003a3f69692c99 in ?? ()
No symbol table info available.
#31 0x00003a3f69692c99 in ?? ()
No symbol table info available.
#32 0x000019e07858aca9 in ?? ()
No symbol table info available.
#33 0x0000340ed0602311 in ?? ()
No symbol table info available.
#34 0x0000000000000000 in ?? ()
No symbol table info available.


registers:
rax            0x7fffe66f9fe0	140737059463136
rbx            0x7fffffffc8e8	140737488341224
rcx            0x1	1
rdx            0x3ff0000000000000	4607182418800017408
rsi            0x24eb288	38711944
rdi            0x7fffffffc520	140737488340256
rbp            0x7ffff5a2a800	0x7ffff5a2a800 <writeSTL(Nan::FunctionCallbackInfo<v8::Value> const&)>
rsp            0x7fffffffc750	0x7fffffffc750
r8             0x24eb210	38711824
r9             0x7ffff7c17060	140737350037600
r10            0x4a6	1190
r11            0x7fffe6444be0	140737056623584
r12            0x7fffffffc7f0	140737488340976
r13            0x7ffff5a1c170	140737314406768
r14            0x0	0
r15            0x229c9f8	36293112
rip            0x7ffff5a1c1cc	0x7ffff5a1c1cc <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+92>
eflags         0x10246	[ PF ZF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0


current instructions:
=> 0x7ffff5a1c1cc <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+92>:	add    $0x10,%rsp
   0x7ffff5a1c1d0 <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+96>:	pop    %rbx
   0x7ffff5a1c1d1 <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+97>:	pop    %rbp
   0x7ffff5a1c1d2 <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+98>:	pop    %r12
   0x7ffff5a1c1d4 <Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)+100>:	retq   
   0x7ffff5a1c1d5:	data16 nopw %cs:0x0(%rax,%rax,1)
   0x7ffff5a1c1e0 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)>:	push   %r13
   0x7ffff5a1c1e2 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+2>:	mov    %rsi,%r13
   0x7ffff5a1c1e5 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+5>:	push   %r12
   0x7ffff5a1c1e7 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+7>:	mov    %rdx,%r12
   0x7ffff5a1c1ea <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+10>:	push   %rbp
   0x7ffff5a1c1eb <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+11>:	mov    %rdi,%rbp
   0x7ffff5a1c1ee <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+14>:	push   %rbx
   0x7ffff5a1c1ef <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+15>:	sub    $0x18,%rsp
   0x7ffff5a1c1f3 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+19>:	mov    (%rdx),%rbx
   0x7ffff5a1c1f6 <Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&)+22>:	add    $0x28,%rbx


threads backtrace:

Thread 9 (Thread 0x7fffdec8a700 (LWP 32523)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fffe403af72 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#2  0x00007fffe403afb9 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#3  0x00007ffff7c25f2a in start_thread (arg=0x7fffdec8a700) at pthread_create.c:463
#4  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffdf08b700 (LWP 32522)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fffe403af72 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#2  0x00007fffe403afb9 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#3  0x00007ffff7c25f2a in start_thread (arg=0x7fffdf08b700) at pthread_create.c:463
#4  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffdf48c700 (LWP 32521)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fffe403af72 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#2  0x00007fffe403afb9 in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#3  0x00007ffff7c25f2a in start_thread (arg=0x7fffdf48c700) at pthread_create.c:463
#4  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ffff7fcf700 (LWP 32519)):
#0  0x00007ffff7c2e706 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x229c940 <node::inspector::(anonymous namespace)::inspector_io_thread_semaphore>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x229c940 <node::inspector::(anonymous namespace)::inspector_io_thread_semaphore>, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7c2e7f8 in __new_sem_wait_slow (sem=sem@entry=0x229c940 <node::inspector::(anonymous namespace)::inspector_io_thread_semaphore>, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007ffff7c2e869 in __new_sem_wait (sem=sem@entry=0x229c940 <node::inspector::(anonymous namespace)::inspector_io_thread_semaphore>) at sem_wait.c:42
#4  0x0000000001574f92 in uv_sem_wait (sem=0x229c940 <node::inspector::(anonymous namespace)::inspector_io_thread_semaphore>) at ../deps/uv/src/unix/thread.c:384
#5  0x00000000013e07ca in node::inspector::(anonymous namespace)::InspectorIoThreadSignalThreadMain(void*) ()
#6  0x00007ffff7c25f2a in start_thread (arg=0x7ffff7fcf700) at pthread_create.c:463
#7  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffff6258700 (LWP 32518)):
#0  0x00007ffff7c2e706 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x22b4660) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x22b4660, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7c2e7f8 in __new_sem_wait_slow (sem=0x22b4660, abstime=0x0) at sem_waitcommon.c:181
#3  0x00000000015833a8 in v8::base::Semaphore::Wait() ()
#4  0x00000000014126f9 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000001415d0c in v8::platform::WorkerThread::Run() ()
#6  0x0000000001585790 in v8::base::ThreadEntry(void*) ()
#7  0x00007ffff7c25f2a in start_thread (arg=0x7ffff6258700) at pthread_create.c:463
#8  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff6a59700 (LWP 32517)):
#0  0x00007ffff7c2e706 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x22b4660) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x22b4660, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7c2e7f8 in __new_sem_wait_slow (sem=0x22b4660, abstime=0x0) at sem_waitcommon.c:181
#3  0x00000000015833a8 in v8::base::Semaphore::Wait() ()
#4  0x00000000014126f9 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000001415d0c in v8::platform::WorkerThread::Run() ()
#6  0x0000000001585790 in v8::base::ThreadEntry(void*) ()
#7  0x00007ffff7c25f2a in start_thread (arg=0x7ffff6a59700) at pthread_create.c:463
#8  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff725a700 (LWP 32516)):
#0  0x00007ffff7c2e706 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x22b4660) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x22b4660, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7c2e7f8 in __new_sem_wait_slow (sem=0x22b4660, abstime=0x0) at sem_waitcommon.c:181
#3  0x00000000015833a8 in v8::base::Semaphore::Wait() ()
#4  0x00000000014126f9 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000001415d0c in v8::platform::WorkerThread::Run() ()
#6  0x0000000001585790 in v8::base::ThreadEntry(void*) ()
#7  0x00007ffff7c25f2a in start_thread (arg=0x7ffff725a700) at pthread_create.c:463
#8  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff7a5b700 (LWP 32515)):
#0  0x00007ffff7c2e706 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x22b4660) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x22b4660, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff7c2e7f8 in __new_sem_wait_slow (sem=0x22b4660, abstime=0x0) at sem_waitcommon.c:181
#3  0x00000000015833a8 in v8::base::Semaphore::Wait() ()
#4  0x00000000014126f9 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000001415d0c in v8::platform::WorkerThread::Run() ()
#6  0x0000000001585790 in v8::base::ThreadEntry(void*) ()
#7  0x00007ffff7c25f2a in start_thread (arg=0x7ffff7a5b700) at pthread_create.c:463
#8  0x00007ffff7b56edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7a5c740 (LWP 32507)):
#0  0x00007fffe4269d2a in StlAPI_Writer::Write(TopoDS_Shape const&, char const*) () from ./node_modules/occ/occt-7.2.0/lib/libTKSTL.so.7
#1  0x00007ffff5a2a95d in writeSTL(Nan::FunctionCallbackInfo<v8::Value> const&) () at /usr/include/c++/8/bits/basic_string.h:2281
#2  0x00007ffff5a1c1cc in Nan::imp::FunctionCallbackWrapper (info=...) at ../node_modules/nan/nan_callbacks_12_inl.h:174
#3  0x0000000000ac4ca3 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#4  0x0000000000b43758 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#5  0x0000000000b44179 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
#6  0x0000321a3960437d in ?? ()
#7  0x0000321a396042c1 in ?? ()
#8  0x00007fffffffc9e0 in ?? ()
#9  0x0000000000000006 in ?? ()
#10 0x00007fffffffca68 in ?? ()
#11 0x0000321a397c2962 in ?? ()
#12 0x0000340ed0602311 in ?? ()
#13 0x000004427f453309 in ?? ()
#14 0x0000000600000000 in ?? ()
#15 0x000013f8b663fe99 in ?? ()
#16 0x000023f225876621 in ?? ()
#17 0x00003a3f69691b69 in ?? ()
#18 0x000004427f453309 in ?? ()
#19 0x000013f8b6638f89 in ?? ()
#20 0x000013f8b663fe99 in ?? ()
#21 0x00003a3f69691b69 in ?? ()
#22 0x00003a3f69692bd9 in ?? ()
#23 0x000019e078583971 in ?? ()
#24 0x00007fffffffcb00 in ?? ()
#25 0x0000321a397c1ef0 in ?? ()
#26 0x00003a3f69692c21 in ?? ()
#27 0x00003a3f69692c49 in ?? ()
#28 0x00003a3f69692b01 in ?? ()
#29 0x00003a3f69692b91 in ?? ()
#30 0x00003a3f69692c99 in ?? ()
#31 0x00003a3f69692c99 in ?? ()
#32 0x000019e07858aca9 in ?? ()
#33 0x0000340ed0602311 in ?? ()
#34 0x0000000000000000 in ?? ()
```
