### ISSUE TITLE
occ.makeBox is not a function

### ISSUE THREAD

**Issue by ceremcem** [OpenWebCAD/node-occ#36]
I've compiled node-occ and tried to run the example code in README. Here is the contents of `example.js`: 

```js
var occ = require('occ')

// construct a box
var box = occ.makeBox([0,0,0],[100,100,50])

// construct a cylinder
var cyl = occ.makeCylinder([50,50,-10],[50,50,60],40)

// cut the box with cylinder
box = occ.cut(box,cyl)

// save result to a STEP file
occ.writeSTEP("somefile.step",box)
```

and here is the error: 

```console 
$ node example.js 
/home/ceremcem/sync/dev/node-occ-example/example.js:4
var box = occ.makeBox([0,0,0],[100,100,50])
              ^

TypeError: occ.makeBox is not a function
    at Object.<anonymous> (/home/ceremcem/sync/dev/node-occ-example/example.js:4:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by erossignon** [comment]
README has a typo please use:
```
var occ = require('occ').occ
```
